apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruler
  namespace: demo
  labels:
    app: ruler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruler
  template:
    metadata:
      labels:
        app: ruler
    spec:
      containers:
        - name: ruler
          image: searchlight/ruler:canary
          imagePullPolicy: Always
          args:
            - "run"
            - "--m3coordinator.url=http://m3coordinator.demo.svc:7201"
            - "--m3query.url=http://m3query.demo.svc:7201"
            - "--ruler.alertmanager-url=http://multi-alertmanager.demo.svc:9094/api/prom/alertmanager"
            - "--ruler.external-url=http://dev.ruler.com"
          ports:
            - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: ruler
  namespace: demo
spec:
  selector:
    app: ruler
  ports:
    - port: 8443
      protocol: TCP
      name: http
  type: ClusterIP
